### ISSUE TITLE
UUID 4 Generation

### ISSUE THREAD

**Issue by FredHappyface** [Geoffery10/MC-Skin-Pack-Creator#3]
Just so you are aware, python provides a method to generate uuid v4 in the stdlib which can save you using requests

https://docs.python.org/3/library/uuid.html#uuid.uuid4

**Comment by Geoffery10** [comment]
Thank you for letting me know I'll look into updating this soon!

**Comment by Geoffery10** [comment]
Resolved with the latest release. Thank you for the suggestion @FredHappyface!
